[pytest]
filterwarnings =
    ignore:.*PULP_CBC_CMD is deprecated.*:DeprecationWarning
    ignore:.*LpVariable.dicts is deprecated.*:DeprecationWarning
    ignore:.*eval_set.*is deprecated.*:UserWarning
